sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 522436
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPtNhA9MA2yS47WfFtV
    access-key-secret: FXVzOCFbv7d6tFDa6Vuu57FZBhLvYo
    bucket-name: 000sky-take-out
